CREATE TABLE "tweets" (
  "tweet_id" bigint PRIMARY KEY,
  "created_at" timestamp NOT NULL,
  "text" varchar(255) NOT NULL,
  "retweet_count" INT NOT NULL,
  "tweet_source" varchar(255) NOT NULL
);

CREATE TABLE "retweets" (
  "tweet_id" bigint,
  "retweet_of_tweet_id" bigint NOT NULL
);

CREATE TABLE "tweetReplys" (
  "tweet_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "in_reply_to_screen_name" varchar(255),
  "in_reply_to_status_id" bigint,
  "in_reply_to_user_id" bigint
);

CREATE TABLE "hashtags" (
  "tweet_id" bigint NOT NULL,
  "hashtag" varchar(144) NOT NULL
);

CREATE TABLE "users" (
  "user_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "user_name" varchar(255),
  "user_screen_name" varchar(255),
  "user_followers_count" INT,
  "user_friends_count" INT,
  "user_lang" varchar(10),
  "user_status_count" varchar(255),
  "user_created_at" timestamp
);

CREATE TABLE "follow" (
  "follower_time" timestamp NOT NULL,
  "following_id" bigint,
  "follower_id" bigint
);

CREATE TABLE "userLocations" (
  "user_id" bigint NOT NULL,
  "city_id" INT
);

CREATE TABLE "country" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" varchar(255) NOT NULL
);

CREATE TABLE "city" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" varchar(255) NOT NULL,
  "country_id" INT
);

CREATE TABLE "userTimeZones" (
  "user_id" bigint NOT NULL,
  "user_time_zone" varchar(127) NOT NULL,
  "user_utc_offset" INT
);

CREATE TABLE "userDesc" (
  "user_id" bigint NOT NULL,
  "user_description" varchar(255) NOT NULL
);

CREATE TABLE "tweets_users" (
  "user_id" bigint NOT NULL,
  "tweet_id" bigint NOT NULL
);

CREATE TABLE "images" (
  "image_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tweet_id" bigint NOT NULL,
  "image_url" varchar(255) NOT NULL
);

CREATE TABLE "videos" (
  "video_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tweet_id" bigint NOT NULL,
  "video_url" varchar(255) NOT NULL,
  "duration_seconds" int
);

ALTER TABLE "follow" ADD FOREIGN KEY ("following_id") REFERENCES "users" ("user_id");

ALTER TABLE "follow" ADD FOREIGN KEY ("follower_id") REFERENCES "users" ("user_id");

ALTER TABLE "userLocations" ADD FOREIGN KEY ("city_id") REFERENCES "country" ("id");

ALTER TABLE "city" ADD FOREIGN KEY ("country_id") REFERENCES "country" ("id");

ALTER TABLE "images" ADD FOREIGN KEY ("tweet_id") REFERENCES "tweets" ("tweet_id");

ALTER TABLE "videos" ADD FOREIGN KEY ("tweet_id") REFERENCES "tweets" ("tweet_id");

ALTER TABLE "retweets" ADD FOREIGN KEY ("tweet_id") REFERENCES "tweets" ("tweet_id");

ALTER TABLE "tweetReplys" ADD FOREIGN KEY ("tweet_id") REFERENCES "tweets" ("tweet_id");

ALTER TABLE "hashtags" ADD FOREIGN KEY ("tweet_id") REFERENCES "tweets" ("tweet_id");

ALTER TABLE "userLocations" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "userTimeZones" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "userDesc" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "tweets_users" ADD FOREIGN KEY ("tweet_id") REFERENCES "tweets" ("tweet_id");

ALTER TABLE "tweets_users" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");
